application:    two-fifty
version:    1
runtime:    python
api_version:    1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "1d"
  mime_type: image/x-icon

- url: /loading-small.gif
  static_files: loading-small.gif
  upload: loading-small.gif
  expiration: "1000d"

- url: /count.js
  static_files: count.js
  upload: count.js

- url: /movie-count-widget.png
  static_files: movie-count-widget.png
  upload: movie-count-widget.png

- url: /seen.js
  static_files: seen.js
  upload: seen.js

- url: /build-reco.js
  static_files: build-reco.js
  upload: build-reco.js

- url: /movie-seen-widget.png
  static_files: movie-seen-widget.png
  upload: movie-seen-widget.png

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /build-reco
  script: build-reco.py

- url: /.*
  script: 250.py
