application:    two-fifty
version:    1
runtime:    python
api_version:    1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  expiration: "1d"
  mime_type: image/x-icon

- url: /loading-small.gif
  static_files: loading-small.gif
  upload: loading-small.gif
  expiration: "1000d"

- url: /count.js
  static_files: count.js
  upload: count.js

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /.*
  script: 250.py
